### ISSUE TITLE
Why not uv?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [panel-extensions/copier-template-panel-extension#4]
Some users might be in an organisation with a very restricted environment. `pixi` is just harder to install than `uv`. `uv` can be installed with `pip`. If you are a windows user you will need to install pixi via a windows installer which might not be allowed or possible. I think there are other ways. But the pixi web site describes so many different ways of installing that it appears complicated. There is no simple, single way to install no matter what.

Furthermore `uv` is a very well known and widely adapted tool already while pixi appears more niche. For example [Ray Bell writes](https://sites.google.com/view/raybellwaves/blog/prefix-dev-tools) he uses pixi for those 10% of projects that are very hard to install and `uv` for the rest.

Please consider migrating from `pixi` to `uv` to ease adaption.

**Comment by MarcSkovMadsen** [comment]
Besides not being able to easily install on windows, I also have challenges on Linux because I'm running on a Jupyterhub inside a Docker container where `/home/jovyan/.bashrc` is readonly. Thus I get

```bash
touch: cannot touch '/home/jovyan/.bashrc': Permission denied
```

when trying to install pixi. This just complicates things.

I have to manually add

```bash
export PATH=$PATH:~/.pixi/bin
```

to my `/home/jovyan/<user-initials>/.bashrc` file.

I never have those problems with `uv`. It just works.

**Comment by MarcSkovMadsen** [comment]
Ahh. Now I need to start a stronger server because `pixi` uses too many resources and my pod is killed. I never have to do that with any of my other tools or projects:

![image](https://github.com/user-attachments/assets/6b6641fc-18cd-4634-a2c5-fa5d1731a12b)

![image](https://github.com/user-attachments/assets/c43a0c85-b058-45a9-a1fd-d0cd048dcf4f)

**Comment by MarcSkovMadsen** [comment]
I think I will just use `uv`. Then hope `pixi` works in Github actions.

**Comment by MarcSkovMadsen** [comment]
Running pytest takes for ever because it needs to update (?) the environments.

![image](https://github.com/user-attachments/assets/8d37ce76-d484-435c-b710-aea53cdc2b51)

And then my pod is killed again

![image](https://github.com/user-attachments/assets/005eb0be-3e4a-4733-b4d1-2169176ae3db)

**Comment by MarcSkovMadsen** [comment]
Ok. I would like to add pandas as a `test` dependency and `narwhals` as a `package` dependency.. Should I add pandas to `dev` environment in pyproject.toml? Should I add it to `test` dependencies in pixi.toml? How? How does that lock file behave and should it be included in my git history?

**Comment by MarcSkovMadsen** [comment]
Ok. I figured out that to select my python interpreter in VS Code I need to manually select `.pixi/envs/default/bin/python`.

**Comment by MarcSkovMadsen** [comment]
Ok. I want to jump into a shell. But its a pretty slow experience as it starts updating all the environments. **It ended up taking 60 secs!**

![image](https://github.com/user-attachments/assets/1215596f-2b19-401b-a338-7b632e11d467)

**Comment by MarcSkovMadsen** [comment]
Ok. I tried to install autocompletion as described in the pixi guide

```bash
echo 'eval "$(pixi completion --shell bash)"' >> /home/jovyan/<my-user-initials>/.bashrc 
```

It corrupted my .bashrc. When I open a terminal I see:

```bash
fi': not a valid identifier
```

The problem is that it does not append to a new line

![image](https://github.com/user-attachments/assets/3df0119e-7a58-41aa-aff1-3c3f3e8842b2)

**Comment by MarcSkovMadsen** [comment]
Ok there is a [VS Code pixi extension](https://marketplace.visualstudio.com/items?itemName=jjjermiah.pixi-vscode) that should make life easier. But unfortunately its not in the [open-vsx.org](https://open-vsx.org/) Market Place that [Code Server](https://github.com/coder/code-server) is using. And I'm working on code-server.

![image](https://github.com/user-attachments/assets/8861d12e-826e-413d-8e06-1a3fa8507de4)

**Comment by MarcSkovMadsen** [comment]
Now I run pytest again. Have to wait 60 s again.

![image](https://github.com/user-attachments/assets/95b72308-59b3-4161-aa8e-34e77e4ecc50)

**Comment by MarcSkovMadsen** [comment]
No.It killed my pod with up to 16 cores and 128 GB RAM!

![image](https://github.com/user-attachments/assets/fe2f0b0f-1932-42ee-9a92-4fdc5d975681)

**Comment by MarcSkovMadsen** [comment]
I don't have time for `pixi`. Will just do `uv pip install -e .[dev]` and go from there.

**Comment by MarcSkovMadsen** [comment]
**I think the problem is that `pixi` (with our configuration?) works perfectly for ci/ cd but not for personal development**. The question is how it can be configured to also work for personal development?

**Comment by ahuang11** [comment]
I don't have a strong preference to pixi as I do to mkdocs because I personally just use conda & pip for my own dev envs.

As far as I understand, uv is a drop in replacement to pip? I'm wondering if there will be any issues with uv compiling Panel JSComponents? I'm also wondering whether hatch is a better replacement?

I don't have much experience in all these beyond pip and conda. I would like to hear what @hoxbro thinks since he brought it into the HoloViz repos.

**Comment by MarcSkovMadsen** [comment]
> I don't have a strong preference to pixi as I do to mkdocs because I personally just use conda & pip for my own dev envs.
> 
> As far as I understand, uv is a drop in replacement to pip? I'm wondering if there will be any issues with uv compiling Panel JSComponents? I'm also wondering whether hatch is a better replacement?
> 
> I don't have much experience in all these beyond pip and conda. I would like to hear what @hoxbro thinks since he brought it into the HoloViz repos.

I don't think `uv`, `conda` or `pixi` is compiling panel jscomponents. Its done with Panel and Node. The challenge can be to get Node installed. You can do that with `conda` or `pixi`. Not `uv`.

**Comment by ahuang11** [comment]
Right, I think that's the supporting argument for pixi, but as you've experienced maybe it's excessive to set up on Windows, and maybe conda is sufficient.

**Comment by MarcSkovMadsen** [comment]
Keeping the `pixi.lock` file up to date is also a mystery for me. How do I do that? I ended up deleting it and running `pixi install again`.

**Comment by MarcSkovMadsen** [comment]
Then `pixi` does not install non-conda packages by default and the error message is not great. For example `mkdocs-pycafe` is not a conda package. Took me some time to figure out cause and solution.

Maybe its obvious for someone working with conda every day. I'm not though.

![image](https://github.com/user-attachments/assets/05fa1482-634b-43cf-988d-027a3199d4d2)

**Comment by MarcSkovMadsen** [comment]
Ok. My docs can't build.

Looks like my package is not installed in the docs environment?

![image](https://github.com/user-attachments/assets/adb72f15-245d-4299-be04-ae46c4d9f60c)

To build docs locally I need

![image](https://github.com/user-attachments/assets/f24b4ac9-05e8-4905-92dd-eefeb3244c17)

Otherwise auto doc won't find my code.

Originally this was `src.panel_copy_paste`. Maybe it needs to be that in ci/cd?

**Comment by MarcSkovMadsen** [comment]
I've changed it back to `src.panel_copy_paste`. Then my docs can build in actions. But docstrings are still not collected.

I've tried to search and figure out how to get `panel_copy_paste` installed in the `docs` pixi environment. But I've not been able to. The docs look stylish. But they are really hard to navigate.

**Comment by MarcSkovMadsen** [comment]
Ok. Figured it out. had to set the `mkdocstrings` `path`:

![image](https://github.com/user-attachments/assets/8d86652b-75df-4b11-8ad4-2b160718a5ac)

**Comment by hoxbro** [comment]
I just want to clarify that I use Pixi as part of my local development, and I'm pretty sure I heard @philippjfr say something similar. We only transitioned to Pixi earlier this year, and before that, we all did what @ahuang11 did and just used a combination of `conda`/`pip` because `pyctdev` was that bad to use. Habits die hard, and I would not force people to use Pixi if they have something that works. 

--- 

I will only go over some of the comments left in this issue. Some of them have already been resolved, but I still want to add some clarification.

> If you are a windows user you will need to install pixi via a windows installer which might not be allowed or possible. I think there are other ways. But the pixi web site describes so many different ways of installing that it appears complicated. There is no simple, single way to install no matter what.

There is a simple way for Windows users to install Pixi: use the installer. However, if you are in a corporate setting that bans this method, you need to dive deeper.  I agree it is not as easy as `pip install`, I don't know why it is unavailable on PyPi. Maybe nobody has asked them?

> For example [Ray Bell writes](https://sites.google.com/view/raybellwaves/blog/prefix-dev-tools) he uses pixi for those 10% of projects that are very hard to install and uv for the rest.

As you later found out, in our case, we need to install non-Python tools, e.g., `node` and `esbuild`. This puts us in the 10% projects, in my opinion. Even if not all templates will need this, it doesn't merit the extra work of doubling the work of having two different workflows. 

> I'm running on a Jupyterhub inside a Docker container where /home/jovyan/.bashrc is readonly. ... I never have those problems with uv. It just works.

I think this is because UV uses the python environment. Maybe this could be helped by `Pixi` adding a symlink to `~/.local/bin` during the installation for Linux users and/or a PyPI package.  

> Now I need to start a stronger server because pixi uses too many resources and my pod is killed

This is a __big__ problem! An open issue is here: https://github.com/prefix-dev/pixi/issues/2458, with a well-known repo.  

> I think the problem is that pixi (with our configuration?) works perfectly for ci/ cd but not for personal development. The question is how it can be configured to also work for personal development?

As I mentioned at the start, it works for personal development. I would be very careful in extrapolating your experience to the general experience, and likewise, I will do the same with my experience. 

I would also say it is a new tool and requires some learning. From the look of it, you only use `uv`'s `pip` interface, not their higher-level API. Reading the documentation could explain some of the problems mentioned. 

FWIW, I have opened a PR on [HoloViews](https://github.com/holoviz/holoviews/pull/6456) and I am discussing with @maximlt around adding a `dev` environment. The environment should be more aligned with the `conda`/`pip` workflow, where you should be able to enable it with `pixi shell -e dev` (still need to update docs).

> I would like to hear what @hoxbro thinks since he brought it into the HoloViz repos.

Mostly because our project depends on some non-Python-only packages, and I wanted to have a unified experience across our repos. These non-packages can roughly be split into: NodeJS (Panel, GeoViews), GPU-support (Datashader, HoloViews, hvplot), and Geo-packages (GeoViews - Not as essential anymore).

**Comment by jjjermiah** [comment]
re: [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=jjjermiah.pixi-vscode) 

With pixi's new features, and changes to the user api, I am working on a full refactor of the vscode extension with new features. 

Thank you for pointing out the open-vsix registry, which I have uploaded the last release to. 

If you have features you would like to see implemented, or ideas to enhance your developer-experience, please don't hesitate to let me know! 

cheers,
